export const JENKINS_UPDATE_RECEIVED = 'JENKINS_UPDATE_RECEIVED';
export const JENKINS_ASYNC_LOAD_FROM_STORAGE = 'JENKINS_ASYNC_LOAD_FROM_STORAGE';
export const JENKINS_DELETE = 'JENKINS_DELETE';
export const JENKINS_DELETE_ALL = 'JENKINS_DELETE_ALL';
