export const JENKINS_UPDATE_RECEIVED = 'JENKINS_UPDATE_RECEIVED';
export const JENKINS_ASYNC_LOAD_FROM_STORAGE = 'JENKINS_ASYNC_LOAD_FROM_STORAGE';
export const JENKINS_DELETE = 'JENKINS_DELETE';
export const JENKINS_DELETE_ALL = 'JENKINS_DELETE_ALL';

export const FORM_GITHUB_LOGIN_UPDATE = 'FORM_GITHUB_LOGIN_UPDATE';
export const FORM_GITHUB_LOGIN_SUCCESS = 'FORM_GITHUB_LOGIN_SUCCESS';
export const FORM_GITHUB_LOGIN_FAIL = 'FORM_GITHUB_LOGIN_FAIL';

export const FETCH_GITHUB_LOGIN = 'FETCH_GITHUB_LOGIN';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
